require('dotenv').config();
const express = require('express');
const path = require('path');
const session = require('express-session');
const pgSession = require('connect-pg-simple')(session);
const { pool } = require('./src/config/db');
const app = express();
const PORT = process.env.PORT || 3000;
app.set('view engine','ejs'); app.set('views',path.join(__dirname,'views'));
app.use(express.urlencoded({extended:true})); app.use(express.json());
app.use('/public',express.static(path.join(__dirname,'public')));
app.use(session({store:new pgSession({pool, createTableIfMissing:true}), secret:process.env.SESSION_SECRET||'change-this-secret', resave:false, saveUninitialized:false, cookie:{maxAge:1000*60*60*8}}));
app.use((req,res,next)=>{res.locals.user=req.session.user||null; res.locals.appName=process.env.APP_NAME||'Smart Data Task Management'; next();});
app.use('/',require('./src/routes/auth'));
app.use('/superadmin',require('./src/routes/superadmin'));
app.use('/employee',require('./src/routes/employee'));
app.use('/client',require('./src/routes/client'));
app.use('/tasks',require('./src/routes/tasks'));
app.use('/complaints',require('./src/routes/complaints'));
app.get('/health',(req,res)=>res.json({ok:true,version:'6.5.0'}));
app.use((req,res)=>res.status(404).render('partials/404'));
app.listen(PORT,()=>console.log(`Smart Data V6.5 running on ${PORT}`));
const qrLocationRoutes = require("./routes/qrLocations");
app.use("/qr-locations", qrLocationRoutes);
